# Generated by Django 4.1.3 on 2022-11-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ['-week_number'], 'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главные страницы'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='week_number',
            field=models.IntegerField(default=0, verbose_name='Номер недели'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='news',
            field=models.TextField(blank=True, verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='work_schedule',
            field=models.TextField(blank=True, verbose_name='Расписание работы'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Working_professions',
        ),
    ]
